// ===== FUNCTION PLOTTER =====
const PC=['#ff6b6b','#4C8DFF','#4ee06b','#fa8c16','#9b59f7'];
const PE2D=[{l:'sin(x)/x',e:'sin(x)/x'},{l:'e^(-x²)',e:'e^(-x^2)'},{l:'x³-3x',e:'x^3-3*x'},{l:'1/x',e:'1/x'},{l:'log(x)',e:'log(x)'},{l:'|x|',e:'abs(x)'},{l:'tan(x)',e:'tan(x)'}];
const PE3D=[{l:'x²+y²',e:'x^2+y^2'},{l:'x²-y²',e:'x^2-y^2'},{l:'sin(x)cos(y)',e:'sin(x)*cos(y)'},{l:'√(x²+y²)',e:'sqrt(x^2+y^2)'},{l:'sin(√(x²+y²))',e:'sin(sqrt(x^2+y^2))'}];
let pm='2d',pf=[{e:'sin(x)/x',c:'#4C8DFF'}],p3e='sin(x)*cos(y)',pci=1;
function plotInit(){plotRenderFuncList();plotRenderExamples();plotRenderConics();}
function plotRenderFuncList(){const c=document.getElementById('plot-func-list');if(!c)return;c.innerHTML='';pf.forEach((f,i)=>{const r=document.createElement('div');r.style.cssText='display:flex;align-items:center;gap:8px;margin-bottom:8px;';r.innerHTML=`<div style="width:12px;height:12px;border-radius:50%;background:${f.c};flex-shrink:0;"></div><input type="text" value="${f.e}" placeholder="e.g. sin(x)/x" class="input" style="flex:1;font-family:'Cambria Math',serif;" oninput="pf[${i}].e=this.value">${pf.length>1?`<button onclick="pf.splice(${i},1);plotRenderFuncList();plotRender();" style="font-size:16px;color:#ff6b6b;background:none;border:none;cursor:pointer;">×</button>`:''}`;c.appendChild(r);});}
function plotAddFunc(){if(pf.length>=5)return;pf.push({e:'',c:PC[pci%PC.length]});pci++;plotRenderFuncList();}
function plotRenderExamples(){const c=document.getElementById('plot-examples');if(!c)return;c.innerHTML='';(pm==='2d'?PE2D:PE3D).forEach(ex=>{const ch=document.createElement('div');ch.style.cssText='padding:6px 12px;background:var(--bg-input);border:1px solid var(--border);border-radius:999px;font-size:12px;color:var(--text-secondary);cursor:pointer;font-family:Cambria Math,serif;';ch.textContent=ex.l;ch.onmouseenter=()=>{ch.style.borderColor='var(--accent)';ch.style.color='var(--accent)';};ch.onmouseleave=()=>{ch.style.borderColor='var(--border)';ch.style.color='var(--text-secondary)';};ch.onclick=()=>{if(pm==='2d'){pf[0].e=ex.e;plotRenderFuncList();plotRender();}else{p3e=ex.e;plotRender();}};c.appendChild(ch);});}
function plotSwitchMode(m){
    pm=m;
    const b2=document.getElementById('plot-mode-2d'),b3=document.getElementById('plot-mode-3d');
    if(m==='2d'){b2.style.color='#fff';b3.style.background='transparent';b3.style.color='var(--text-secondary)';}
    else{b3.style.color='#fff';b2.style.background='transparent';b2.style.color='var(--text-secondary)';}
    // Liquid indicator carries the active background (init.js); fall back to
    // solid button backgrounds when the effect layer is unavailable.
    if(window.__plotGooeyMove){
        b2.style.background='transparent';b3.style.background='transparent';
        window.__plotGooeyMove(m);
    }else if(m==='2d'){b2.style.background='var(--accent)';}
    else{b3.style.background='var(--accent)';}
    plotRenderExamples();plotRender();
}
function plotRender(){if(pm==='2d')plot2D();else plot3D();}
function plot2D(){const xm=parseFloat(document.getElementById('plot-xmin').value)||-5,xx=parseFloat(document.getElementById('plot-xmax').value)||5;const ye=document.getElementById('plot-ymin'),ye2=document.getElementById('plot-ymax');const ym=ye&&ye.value?parseFloat(ye.value):null,yx=ye2&&ye2.value?parseFloat(ye2.value):null;const tr=[],v=[];pf.forEach((f,i)=>{if(!f.e.trim())return;try{const c=math.compile(f.e),xs=[],ys=[];for(let j=0;j<=500;j++){const x=xm+(xx-xm)*j/500;try{const y=c.evaluate({x});if(typeof y==='number'&&isFinite(y)){xs.push(x);ys.push(y);}else{xs.push(x);ys.push(null);}}catch(e){xs.push(x);ys.push(null);}}tr.push({x:xs,y:ys,type:'scatter',mode:'lines',name:`f${i+1}=${f.e}`,line:{color:f.c,width:2.5}});v.push(f.e);}catch(e){}});if(!tr.length){document.getElementById('plot-status').textContent='No valid functions';return;}Plotly.newPlot('plot-canvas',tr,{paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{color:'#9aa3af',size:12},xaxis:{gridcolor:'#2d3142',zerolinecolor:'#4a5060',range:[xm,xx],title:{text:'x'}},yaxis:{gridcolor:'#2d3142',zerolinecolor:'#4a5060',range:ym!==null&&yx!==null?[ym,yx]:undefined,title:{text:'y'}},margin:{l:50,r:20,t:20,b:40},legend:{x:.02,y:.98,bgcolor:'rgba(26,29,41,.8)',font:{size:11}}},{responsive:true,scrollZoom:true});document.getElementById('plot-status').textContent=`${v.length} function(s): ${v.join(', ')}`;}
function plot3D(){if(!p3e.trim()){document.getElementById('plot-status').textContent='Enter surface';return;}let c;try{c=math.compile(p3e);}catch(e){document.getElementById('plot-status').textContent='Invalid:'+e.message;return;}const N=50,xm=-5,xx=5,ym=-5,yx=5,xV=[],yV=[],zM=[];for(let j=0;j<=N;j++)xV.push(xm+(xx-xm)*j/N);for(let j=0;j<=N;j++)yV.push(ym+(yx-ym)*j/N);for(let i=0;i<=N;i++){const x=xm+(xx-xm)*i/N,zR=[];for(let j=0;j<=N;j++){const y=ym+(yx-ym)*j/N;try{const z=c.evaluate({x,y});zR.push(typeof z==='number'&&isFinite(z)?z:0);}catch(e){zR.push(0);}}zM.push(zR);}Plotly.newPlot('plot-canvas',[{type:'surface',x:xV,y:yV,z:zM,colorscale:'Viridis',contours:{z:{show:true,usecolormap:true,highlightcolor:'#00d4ff',project:{z:true}}}}],{paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{color:'#9aa3af',size:12},scene:{xaxis:{title:'x',gridcolor:'#2d3142',showbackground:false},yaxis:{title:'y',gridcolor:'#2d3142',showbackground:false},zaxis:{title:'z',gridcolor:'#2d3142',showbackground:false},camera:{eye:{x:1.5,y:1.5,z:1}},aspectmode:'data'},margin:{l:0,r:0,t:0,b:0}},{responsive:true,scrollZoom:true});document.getElementById('plot-status').textContent=`Surface: z=${p3e} (${N}×${N})`;}
function plotReset(){document.getElementById('plot-xmin').value='-5';document.getElementById('plot-xmax').value='5';document.getElementById('plot-ymin').value='';document.getElementById('plot-ymax').value='';plotRender();}
function plotClear(){pf=[{e:'',c:'#4C8DFF'}];pci=1;plotRenderFuncList();Plotly.purge('plot-canvas');document.getElementById('plot-status').textContent='Cleared';}
// Conics
const PC_TYPES=[{t:'circle',l:'Circle'},{t:'ellipse',l:'Ellipse'},{t:'parabola',l:'Parabola'},{t:'hyperbola',l:'Hyperbola'}];
const PC_PARAMS={circle:[{id:'r',l:'Radius r',def:3},{id:'cx',l:'Center x',def:0},{id:'cy',l:'Center y',def:0}],ellipse:[{id:'a',l:'Semi-axis a',def:4},{id:'b',l:'Semi-axis b',def:2},{id:'cx',l:'Center x',def:0},{id:'cy',l:'Center y',def:0}],parabola:[{id:'pa',l:'Coefficient a',def:.5}],hyperbola:[{id:'ha',l:'Semi-axis a',def:2},{id:'hb',l:'Semi-axis b',def:2}]};
let currentPlotConicType='';
function plotRenderConics(){const c=document.getElementById('plot-conics');if(!c)return;c.innerHTML='';PC_TYPES.forEach(it=>{const ch=document.createElement('div');ch.style.cssText='padding:6px 12px;background:var(--bg-input);border:1px solid var(--border);border-radius:999px;font-size:12px;color:var(--text-secondary);cursor:pointer;font-family:Cambria Math,serif;';ch.textContent=it.l;ch.onclick=()=>plotSetupConic(it.t);c.appendChild(ch);});}
function plotGetCV(id){const e=document.getElementById('pc-'+id);return e?parseFloat(e.value):0;}
function plotSetupConic(t){currentPlotConicType=t;document.getElementById('plot-conic-params').style.display='';const ps=PC_PARAMS[t]||[];document.getElementById('plot-conic-fields').innerHTML=ps.map(p=>`<div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;"><span style="font-size:11px;width:80px;color:var(--text-secondary);">${p.l}:</span><input type="number" id="pc-${p.id}" value="${p.def}" step="0.5" class="input" style="width:70px;text-align:center;font-size:13px;"></div>`).join('');plotDrawConic(t);}
function plotDrawConic(t){const tr=[],N=200,tA=[];for(let i=0;i<=N;i++)tA.push(-Math.PI+2*Math.PI*i/N);
    if(t==='circle'){const r=plotGetCV('r')||3,cx=plotGetCV('cx'),cy=plotGetCV('cy');tr.push({x:tA.map(t=>cx+r*Math.cos(t)),y:tA.map(t=>cy+r*Math.sin(t)),type:'scatter',mode:'lines',name:`Circle r=${r}`,line:{color:'#4C8DFF',width:3}});}
    else if(t==='ellipse'){const a=plotGetCV('a')||4,b=plotGetCV('b')||2,cx=plotGetCV('cx'),cy=plotGetCV('cy');tr.push({x:tA.map(t=>cx+a*Math.cos(t)),y:tA.map(t=>cy+b*Math.sin(t)),type:'scatter',mode:'lines',name:`Ellipse a=${a} b=${b}`,line:{color:'#fa8c16',width:3}});const c=Math.sqrt(Math.abs(a*a-b*b));tr.push({x:[cx-c,cx+c],y:[cy,cy],type:'scatter',mode:'markers',name:'Foci',marker:{color:'#ff6b6b',size:8}});}
    else if(t==='parabola'){const a=plotGetCV('pa')||.5,xs=[],ys=[];for(let x=-10;x<=10;x+=.1){xs.push(x);ys.push(a*x*x);}tr.push({x:xs,y:ys,type:'scatter',mode:'lines',name:`y=${a}x²`,line:{color:'#4ee06b',width:3}});tr.push({x:[0],y:[1/(4*a)],type:'scatter',mode:'markers+text',text:['Focus'],name:'Focus',marker:{color:'#ff6b6b',size:10}});}
    else if(t==='hyperbola'){const a=plotGetCV('ha')||2,b=plotGetCV('hb')||2,tH=[];for(let i=0;i<=N;i++)tH.push(-3+6*i/N);tr.push({x:tH.map(t=>a*Math.cosh(t)),y:tH.map(t=>b*Math.sinh(t)),type:'scatter',mode:'lines',name:'Hyperbola R',line:{color:'#9b59f7',width:3}});tr.push({x:tH.map(t=>-a*Math.cosh(t)),y:tH.map(t=>b*Math.sinh(t)),type:'scatter',mode:'lines',name:'Hyperbola L',line:{color:'#9b59f7',width:3}});const xa=[-15,15];tr.push({x:xa,y:xa.map(x=>(b/a)*x),type:'scatter',mode:'lines',name:'Asymptote',line:{color:'#6b7280',width:1,dash:'dash'}});tr.push({x:xa,y:xa.map(x=>-(b/a)*x),type:'scatter',mode:'lines',name:'Asymptote',line:{color:'#6b7280',width:1,dash:'dash'}});}
    const xm=parseFloat(document.getElementById('plot-xmin').value)||-5,xx=parseFloat(document.getElementById('plot-xmax').value)||5;
    Plotly.newPlot('plot-canvas',tr,{paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{color:'#9aa3af',size:12},xaxis:{gridcolor:'#2d3142',zerolinecolor:'#4a5060',range:[xm,xx],title:{text:'x'},scaleanchor:'y',scaleratio:1},yaxis:{gridcolor:'#2d3142',zerolinecolor:'#4a5060',title:{text:'y'}},margin:{l:50,r:20,t:20,b:40},legend:{x:.02,y:.98,bgcolor:'rgba(26,29,41,.8)',font:{size:11}}},{responsive:true,scrollZoom:true});document.getElementById('plot-status').textContent=`Conic: ${t} rendered`;}

