"""
SymPy Executor for Tool-integrated Reasoning (ToRA mode)
Safely executes Python/SymPy code generated by the model.
"""
import io
import signal
import sympy as sp
from contextlib import redirect_stdout, redirect_stderr
from typing import Dict, Any, Optional


class SymPyExecutor:
    """
    Safe executor for SymPy code in a restricted environment.
    Used by Lane B ToRA mode to verify symbolic calculations.
    """

    # Pre-injected symbols
    DEFAULT_SYMBOLS = {
        'x': sp.Symbol('x'),
        'y': sp.Symbol('y'),
        'z': sp.Symbol('z'),
        't': sp.Symbol('t'),
        'n': sp.Symbol('n'),
        'k': sp.Symbol('k'),
        'm': sp.Symbol('m'),
        'a': sp.Symbol('a'),
        'b': sp.Symbol('b'),
        'c': sp.Symbol('c'),
        'pi': sp.pi,
        'oo': sp.oo,
        'inf': sp.oo,
        'I': sp.I,  # imaginary unit
    }

    def __init__(self, timeout: int = 5):
        self.timeout = timeout
        self.globals = self._build_safe_globals()

    def _build_safe_globals(self) -> Dict[str, Any]:
        """Build restricted execution environment."""
        builtins = {
            'abs': abs, 'max': max, 'min': min, 'sum': sum,
            'range': range, 'len': len, 'str': str,
            'float': float, 'int': int, 'complex': complex,
            'round': round, 'pow': pow, 'divmod': divmod,
            'True': True, 'False': False, 'None': None,
            'print': print,
        }

        safe_globals = {'__builtins__': builtins}

        # Inject sympy
        safe_globals['sympy'] = sp
        safe_globals['sp'] = sp

        # Core sympy functions
        safe_globals['Symbol'] = sp.Symbol
        safe_globals['symbols'] = sp.symbols
        safe_globals['integrate'] = sp.integrate
        safe_globals['diff'] = sp.diff
        safe_globals['limit'] = sp.limit
        safe_globals['summation'] = sp.summation
        safe_globals['product'] = sp.product
        safe_globals['series'] = sp.series
        safe_globals['solve'] = sp.solve
        safe_globals['solveset'] = sp.solveset
        safe_globals['simplify'] = sp.simplify
        safe_globals['expand'] = sp.expand
        safe_globals['factor'] = sp.factor
        safe_globals['collect'] = sp.collect
        safe_globals['cancel'] = sp.cancel
        safe_globals['apart'] = sp.apart
        safe_globals['trigsimp'] = sp.trigsimp
        safe_globals['powsimp'] = sp.powsimp
        safe_globals['logcombine'] = sp.logcombine

        # Matrix
        safe_globals['Matrix'] = sp.Matrix
        safe_globals['eye'] = sp.eye
        safe_globals['diag'] = sp.diag
        safe_globals['zeros'] = sp.zeros
        safe_globals['ones'] = sp.ones

        # Number theory / special
        safe_globals['Rational'] = sp.Rational
        safe_globals['Integer'] = sp.Integer
        safe_globals['Float'] = sp.Float
        safe_globals['sqrt'] = sp.sqrt
        safe_globals['cbrt'] = sp.cbrt
        safe_globals['root'] = sp.root
        safe_globals['exp'] = sp.exp
        safe_globals['log'] = sp.log
        safe_globals['ln'] = sp.log
        safe_globals['sin'] = sp.sin
        safe_globals['cos'] = sp.cos
        safe_globals['tan'] = sp.tan
        safe_globals['sec'] = sp.sec
        safe_globals['csc'] = sp.csc
        safe_globals['cot'] = sp.cot
        safe_globals['asin'] = sp.asin
        safe_globals['acos'] = sp.acos
        safe_globals['atan'] = sp.atan
        safe_globals['sinh'] = sp.sinh
        safe_globals['cosh'] = sp.cosh
        safe_globals['tanh'] = sp.tanh
        safe_globals['asin'] = sp.asin
        safe_globals['acos'] = sp.acos
        safe_globals['atan'] = sp.atan
        safe_globals['factorial'] = sp.factorial
        safe_globals['binomial'] = sp.binomial
        safe_globals['gamma'] = sp.gamma
        safe_globals['zeta'] = sp.zeta

        # Calculus helpers
        safe_globals['oo'] = sp.oo
        safe_globals['pi'] = sp.pi
        safe_globals['E'] = sp.E
        safe_globals['EulerGamma'] = sp.EulerGamma
        safe_globals['GoldenRatio'] = sp.GoldenRatio

        # Default symbols
        safe_globals.update(self.DEFAULT_SYMBOLS)

        return safe_globals

    def execute(self, code: str, timeout: Optional[int] = None) -> Dict[str, Any]:
        """
        Execute Python code safely.

        Returns:
            {
                'success': bool,
                'result': str,        # String representation
                'latex': str,         # LaTeX if available
                'error': str,         # Error message if failed
                'type': str,          # Result type name
                'stdout': str,        # Captured stdout
                'stderr': str,        # Captured stderr
            }
        """
        timeout = timeout or self.timeout

        def timeout_handler(signum, frame):
            raise TimeoutError(f"Execution exceeded {timeout} seconds")

        # Set up timeout (Unix only; Windows needs different approach)
        try:
            old_handler = signal.signal(signal.SIGALRM, timeout_handler)
            signal.alarm(timeout)
        except (AttributeError, ValueError):
            # Windows or SIGALRM not available
            old_handler = None

        stdout_capture = io.StringIO()
        stderr_capture = io.StringIO()

        try:
            with redirect_stdout(stdout_capture), redirect_stderr(stderr_capture):
                result = eval(code, self.globals, {})

            # Cancel timeout
            if old_handler is not None:
                signal.alarm(0)
                signal.signal(signal.SIGALRM, old_handler)

            # Format result
            result_str = str(result)
            latex_str = ""
            try:
                if hasattr(result, 'latex'):
                    latex_str = result.latex()
                elif hasattr(sp, 'latex'):
                    latex_str = sp.latex(result)
            except Exception:
                pass

            return {
                'success': True,
                'result': result_str,
                'latex': latex_str,
                'error': '',
                'type': type(result).__name__,
                'stdout': stdout_capture.getvalue(),
                'stderr': stderr_capture.getvalue(),
            }

        except TimeoutError as e:
            if old_handler is not None:
                signal.signal(signal.SIGALRM, old_handler)
            return {
                'success': False,
                'result': '',
                'latex': '',
                'error': f'Timeout after {timeout}s: {e}',
                'type': '',
                'stdout': stdout_capture.getvalue(),
                'stderr': stderr_capture.getvalue(),
            }
        except Exception as e:
            if old_handler is not None:
                signal.alarm(0)
                signal.signal(signal.SIGALRM, old_handler)
            return {
                'success': False,
                'result': '',
                'latex': '',
                'error': f'{type(e).__name__}: {e}',
                'type': '',
                'stdout': stdout_capture.getvalue(),
                'stderr': stderr_capture.getvalue(),
            }

    def verify_expression(self, expr1: str, expr2: str) -> Dict[str, Any]:
        """
        Verify if two expressions are mathematically equivalent.
        Both expressions are evaluated and their difference is simplified.
        """
        try:
            r1 = self.execute(expr1)
            r2 = self.execute(expr2)

            if not r1['success'] or not r2['success']:
                return {
                    'equivalent': False,
                    'error': f"Failed to evaluate: {r1.get('error') or r2.get('error')}",
                    'result1': r1.get('result'),
                    'result2': r2.get('result'),
                }

            # Try symbolic comparison
            diff_code = f"simplify(({r1['result']}) - ({r2['result']}))"
            diff_result = self.execute(diff_code)

            is_zero = diff_result['success'] and (
                diff_result['result'] == '0' or
                '0' in diff_result['result'].replace(' ', '')
            )

            return {
                'equivalent': is_zero,
                'difference': diff_result.get('result'),
                'error': '',
                'result1': r1['result'],
                'result2': r2['result'],
            }

        except Exception as e:
            return {
                'equivalent': False,
                'error': str(e),
                'result1': None,
                'result2': None,
            }
